### Список всех десерты
GET /api/dessert/getall HTTP/1.1
Host: localhost:7000


### Список всех десертов
GET /api/dessert/getall/200 HTTP/1.1
Host: localhost:7000

### Получить один десерт
GET /api/dessert/getone/3 HTTP/1.1
Host: localhost:7000


### Создать новый десерт
POST /api/dessert/create HTTP/1.1
Host: localhost:7000
Content-type: application/json; charset=utf-8

{
    "name": "Круассан с клубникой",
    "price": "200"
}

### Обновить десерты
PUT /api/dessert/update/2 HTTP/1.1
Host: localhost:7000
Content-type: application/json; charset=utf-8

{
    "name": "Круассан с клубникой",
    "price": "150"
    }

### Удалить десерт
DELETE /api/dessert/delete/1 HTTP/1.1
Host: localhost:7000
